import React from "react";

const PrivacyPolicy = () => (
  <div className="bg-white py-12">
    <div className="container mx-auto px-6 max-w-4xl">
      <div className="prose prose-lg max-w-none text-gray-700">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">
          CrystalView.ai Privacy Policy
        </h1>
        <p className="text-sm text-gray-500">
          <strong>Effective Date:</strong> 08/01/2025
          <br />
          <strong>Last Updated:</strong> 08/01/2025
        </p>

        <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
          1. Introduction
        </h2>
        <p>
          Welcome to CrystalView. We are a company operating out of California,
          and we are committed to protecting the privacy and security of your
          personal information. This Privacy Policy is designed to help you
          understand how we collect, use, and safeguard your data when you use
          our AI financial application and services (the "Services").
        </p>
        <p>
          By using our Services, you consent to the data practices described in
          this policy. We serve a global user base and, as such, have designed
          this policy to meet the standards of the most stringent global privacy
          regulations, including but not limited to the California Consumer
          Privacy Act (CCPA) and the General Data Protection Regulation (GDPR).
        </p>

        <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
          2. Data We Collect
        </h2>
        <p>
          We collect information to provide, improve, and secure our Services.
          The types of data we collect depend on how you interact with our
          application.
        </p>
        <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">
          Personal Information
        </h3>
        <p>
          This is information that can be used to identify you directly. It
          includes:
        </p>
        <ul>
          <li>
            <strong>Contact Information:</strong> your name, email address, phone
            number, etc.
          </li>
          <li>
            <strong>Account Information:</strong> your username and password,
            security questions, or other credentials, etc
          </li>
          <li>
            <strong>Sensitive Financial Information:</strong> Because our
            Services involve connecting with your financial systems, we collect
            and process sensitive information. This may include credentials for
            connecting into your financial systems.
          </li>
        </ul>
        <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">
          Client Metadata and Usage Data
        </h3>
        <p>
          This is information generated by your use of our Services. It helps us
          understand how our application is being used and how we can improve
          it. This may include:
        </p>
        <ul>
          <li>
            <strong>Usage Information:</strong> data on how you use our
            application, pages you visit, features you interact with, queries
            that you ask the system and any feedback you provide.
          </li>
          <li>
            <strong>Device Information:</strong> We may also store your IP
            address, device type, operating system, browser type.
          </li>
          <li>
            <strong>Log Data:</strong> logs of your activities on our platform.
          </li>
          <li>
            <strong>Aggregated Data:</strong> We may aggregate or anonymize data
            to create statistical or demographic information. This data cannot
            be used to identify you and is used for research and development.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
          3. How We Use Your Data
        </h2>
        <p>We use the data we collect for the following purposes:</p>
        <ul>
          <li>
            <strong>To Provide and Manage our Services:</strong> To connect to
            your financial accounts, analyze your financial data, and provide
            the core functionality of our AI application.
          </li>
          <li>
            <strong>To Store Credentials:</strong> To provide a seamless
            experience, we store your financial credentials in a highly secure,
            encrypted manner. This allows our AI to access your financial data
            and provide continuous service without requiring you to re-enter
            your credentials repeatedly.
          </li>
          <li>
            <strong>To Improve and Personalize our Services:</strong> To analyze
            user trends, train our AI models, and customize the Services to your
            needs.
          </li>
          <li>
            <strong>To Communicate with You:</strong> To send you service
            updates, security alerts, and customer support messages. We may also
            send you marketing communications, but you can opt out at any time.
          </li>
          <li>
            <strong>For Security and Fraud Prevention:</strong> To protect
            against unauthorized access, fraud, and other malicious activity.
          </li>
          <li>
            <strong>For Legal and Regulatory Compliance:</strong> To meet our
            legal obligations and respond to legal requests from courts, law
            enforcement, or other government bodies.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
          4. How We Store and Protect Your Data
        </h2>
        <p>
          We are committed to the security of your data. We use a variety of
          technical and organizational measures to protect your information:
        </p>
        <ul>
          <li>
            <strong>Encryption:</strong> We encrypt all sensitive data,
            including financial credentials, both in transit and at rest.
          </li>
          <li>
            <strong>Access Controls:</strong> Access to your data is restricted
            to authorized personnel who have a legitimate business need.
          </li>
          <li>
            <strong>Regular Audits:</strong> We conduct regular security audits
            and vulnerability assessments to maintain the highest level of
            security.
          </li>
          <li>
            <strong>Data Retention:</strong> We only retain your personal data
            for as long as necessary to fulfill the purposes for which it was
            collected, including for satisfying any legal, accounting, or
            reporting requirements. For financial records, this may be dictated
            by regulatory requirements (e.g., 7 years).
          </li>
        </ul>

        <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
          5. How We Share Your Data
        </h2>
        <p>
          We do not sell your personal information. We may share your data in
          the following limited circumstances:
        </p>
        <ul>
          <li>
            <strong>Third-Party Service Providers:</strong> We use trusted
            third-party service providers to help us operate our business, such
            as cloud hosting providers, data analytics services, and customer
            support platforms. These providers are contractually obligated to
            protect your data and only use it for the purposes we specify.
          </li>
          <li>
            <strong>Financial Institutions:</strong> We may share data with
            financial institutions as necessary to provide our Services, with
            your explicit consent.
          </li>
          <li>
            <strong>Legal Compliance:</strong> We may disclose your information
            if we are required to do so by law, such as to comply with a
            subpoena or other legal process.
          </li>
          <li>
            <strong>Business Transfers:</strong> If we are involved in a merger,
            acquisition, or sale of assets, your information may be transferred
            as part of that transaction. We will notify you of any such change.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
          6. Your Privacy Rights
        </h2>
        <p>
          You have certain rights regarding your personal data. We are committed
          to honoring those rights.
        </p>
        <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">
          Global Rights
        </h3>
        <ul>
          <li>
            <strong>Right to Access:</strong> You have the right to request a
            copy of the personal information we hold about you.
          </li>
          <li>
            <strong>Right to Rectification:</strong> You can request that we
            correct any inaccurate or incomplete personal information we have
            about you.
          </li>
          <li>
            <strong>Right to Deletion:</strong> You can request that we delete
            your personal information, subject to certain exceptions (e.g., to
            comply with a legal obligation).
          </li>
          <li>
            <strong>Right to Portability:</strong> You have the right to receive
            your personal data in a structured, commonly used, and
            machine-readable format.
          </li>
          <li>
            <strong>Right to Object:</strong> You can object to our processing
            of your personal data for certain purposes, such as direct
            marketing.
          </li>
        </ul>
        <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">
          California-Specific Rights (CCPA/CPRA)
        </h3>
        <p>If you are a California resident, you have additional rights:</p>
        <ul>
          <li>
            <strong>Right to Opt-Out of Sale or Sharing:</strong> We do not sell
            or share your personal information. If our practices change, we will
            provide a clear "Do Not Sell or Share My Personal Information"
            link.
          </li>
          <li>
            <strong>Right to Limit Sensitive Personal Information:</strong> You
            have the right to limit the use and disclosure of your sensitive
            personal information to specific purposes. Our use of your sensitive
            financial information is strictly limited to providing you with the
            Services you have requested.
          </li>
        </ul>
        <h3 className="text-xl font-semibold text-gray-800 mt-6 mb-3">
          EU/UK-Specific Rights (GDPR)
        </h3>
        <p>
          If you are a resident of the European Union or the United Kingdom, you
          have additional rights:
        </p>
        <ul>
          <li>
            <strong>Lawful Basis:</strong> We will process your data based on a
            lawful basis, such as your explicit consent or our contractual
            relationship with you.
          </li>
          <li>
            <strong>Right to Lodge a Complaint:</strong> You have the right to
            lodge a complaint with a supervisory authority.
          </li>
        </ul>
        <p>
          To exercise any of these rights, please contact us using the details
          in the "Contact Us" section below.
        </p>

        <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
          7. Children's Privacy
        </h2>
        <p>
          Our Services are not intended for children under the age of 16. We do
          not knowingly collect personal information from children without
          parental consent. If you are a parent or guardian and believe we have
          collected information from your child, please contact us immediately.
        </p>

        <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
          8. Changes to this Policy
        </h2>
        <p>
          We may update this Privacy Policy from time to time. When we make
          significant changes, we will notify you by a prominent notice on our
          website. The updated policy will be effective as of the "Last
          Updated" date.
        </p>

        <h2 className="text-2xl font-semibold text-gray-800 mt-8 mb-4">
          9. Contact Us
        </h2>
        <p>
          If you have any questions about this Privacy Policy or wish to
          exercise your privacy rights, please contact us at:
        </p>
        <p>
          Email:{" "}
          <a
            href="mailto:contact@crystalview.ai"
            className="text-indigo-600 hover:underline"
          >
            contact@crystalview.ai
          </a>
        </p>
      </div>
    </div>
  </div>
);

export default PrivacyPolicy;
